// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ZopMdMuRD4M3F9tLVRHd4vdz2c7-NZg',
    appId: '1:507340658772:web:8aa902e0a3f5897768b5c1',
    messagingSenderId: '507340658772',
    projectId: 'uthm-campustrade',
    authDomain: 'uthm-campustrade.firebaseapp.com',
    storageBucket: 'uthm-campustrade.firebasestorage.app',
    measurementId: 'G-M01V41L0YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB6YWLKLBzM5X-mEKtsyAZ7L2uv8KH4kk',
    appId: '1:507340658772:android:76ac166224cfecc268b5c1',
    messagingSenderId: '507340658772',
    projectId: 'uthm-campustrade',
    storageBucket: 'uthm-campustrade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCReO7RAjn5ZKVMscHRcdAuMfSiVj0S8WM',
    appId: '1:143669552877:ios:f8d35f2584b9850b03cee4',
    messagingSenderId: '143669552877',
    projectId: 'uthmcampustradedatabase',
    storageBucket: 'uthmcampustradedatabase.firebasestorage.app',
    iosBundleId: 'my.edu.uthm.camp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCReO7RAjn5ZKVMscHRcdAuMfSiVj0S8WM',
    appId: '1:143669552877:ios:73f5e828a9050fe803cee4',
    messagingSenderId: '143669552877',
    projectId: 'uthmcampustradedatabase',
    storageBucket: 'uthmcampustradedatabase.firebasestorage.app',
    iosBundleId: 'io.flutter.examples.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0wIeTmNX9uWJMCkRv2exeeeINJcyc07o',
    appId: '1:143669552877:web:dc97a146ee8dea1903cee4',
    messagingSenderId: '143669552877',
    projectId: 'uthmcampustradedatabase',
    authDomain: 'uthmcampustradedatabase.firebaseapp.com',
    storageBucket: 'uthmcampustradedatabase.firebasestorage.app',
    measurementId: 'G-37M9YYENQX',
  );
}
